name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Or any branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: '3.8'  # Match the Python version used by your application
      
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
      
    # - name: Zip the application
    #   run: zip -r application.zip . -x "*.git*" "/*"

    - name: Load secret
      uses: 1password/load-secrets-action@v1
      with:
        # Export loaded secrets as environment variables
        export-env: true
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        SECRET: "op://Production/API KEY/credential"

    - name: Print masked secret
      run: echo "$SECRET"
        # Prints: Secret: ***
      
    # - name: Deploy to AWS Elastic Beanstalk
    #   uses: einaregilsson/beanstalk-deploy@v18
    #   with:
    #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     region: ${{ secrets.AWS_REGION }}
    #     application_name: ${{ secrets.APPLICATION_NAME }}
    #     environment_name: ${{ secrets.ENVIRONMENT_NAME }}
    #     version_label: ${{ github.sha }}
    #     deployment_package: application.zip
