name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Or any branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Match the Python version used by your application
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip freeze > requirements.txt
        
    - name: Zip application for deployment
      run: zip -r application.zip . -x "*.git*"

    - name: Load secret
      uses: 1password/load-secrets-action@v1
      with:
        # Export loaded secrets as environment variables
        export-env: true
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        APIKEY: "op://Service Account Vault/API KEY/credential"
        #AWS_ACCESS_KEY: "op://Service Account Vault/AWS IAM User/username"
        #AWS_SECRET_KEY: "op://Service Account Vault/AWS IAM User/credential"
        AWS_REGION: "us-west-2"
        APPLICATION_NAME: "Stripe Test"
        ENVIRONMENT_NAME: "StripeTest-env"
      
    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        region: "us-west-2"
        application_name: "Stripe Test"
        environment_name: "StripeTest-env"
        version_label: "1.4"
        deployment_package: application.zip
